easy_admin:
    entities:
        # List the entity class name you want to manage
        - App\Entity\Produit
        - App\Entity\Auteur
        - App\Entity\Genre
        - App\Entity\Editeur
        - App\Entity\Fournisseur
